name: audio_toolbox_framework
description: ffi bindings for the AudioToolbox Framework
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  core_foundation_framework: ^0.1.0
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^6.0.1
  test: ^1.16.0
